### PR TITLE
Added student search feature file, fixed small typo

### PR DESCRIPTION
**Pull request by shteveno**
Added the following user story:

PT #152770443

As a student,
If I search for a keyword in the problems list,
Then I should see all the problems relevant to that keyword.

At the moment, users do not have access to the search functionality on the problems view. A flash message appears saying that they don't have permission to access the search page. The new feature file tests that the flash message should not appear and that the student successfully restricts the search results.

Also, made a quick typo fix to student_login.feature

### CODE REVIEW

**Comment by anokhikastia** [comment]
Should we change the user story to the format of:As a ..... So that .... I ..... instead of what we have now? example from lecture: 
As a box office manager
So that I can induce a patron to buy a ticket
I want to show her which Facebook friends are going to a given show

**Comment by shteveno** [comment]
I agree with Anokhi, but would like to hear other opinions

**Comment by Laralinmcc** [comment]
I think the original story that Steven has is fine. After reviewing I say merge!

**Comment by mrinasugosh** [comment]
I think the story looks fine too. As...If...Then and As...So....I seem quite synonymous. I would give it a go to merge.

**Pull request merged**
