### PR TITLE
Detecting Identical Questions feature

### PR DESCRIPTION
**Pull request by mrinasugosh**
PTID: 152624808

After a user uploads questions,
If identical questions are found,
Then the view tells the user that identical questions have been found

As a part of this feature request, remove the near duplicate questions as well.

We will be implementing the view for this feature and additional functionality to handle with identical questions after upload in iteration4.

### CODE REVIEW

**Comment by willsheng** [comment]
looks good to me

**Comment by Laralinmcc** [comment]
Great. Nice that the legacy code is commented at the bottom!

**Comment by mrinasugosh** [comment]
Credit goes to Juwon on that one :)

**Comment by juwon-k** [comment]
Hi all, just a quick note, this is just a rollout of the feature without the rest of the epic. We can add more integration tests once we've implemented the complete Uploads page with the Delete option.

**Comment by anokhikastia** [comment]
looks good to me!

**Pull request merged**
