### PR TITLE
revert clip source code button color change

### PR DESCRIPTION
**Pull request by willsheng**
PTID: #152774586
This removes the clip source code button turning blue on click.

### CODE REVIEW

**Comment by shteveno** [comment]
Okay, looks like this is what Steven Wu was asking for. I approve!

**Comment by juwon-k** [comment]
We had something failing for this feature, is that resolved?

**Comment by willsheng** [comment]
@juwon yes the failing feature should be resolved now

**Comment by mrinasugosh** [comment]
Looks good to me...

**Pull request merged**
