### PR TITLE
Fixed student search bug

### PR DESCRIPTION
**Pull request by shteveno**
PTID: #152770443

We made sure to allow Students access to manage problems and search for questions, especially if the github login does not work as intended. One bug fix for a future iteration is to debug create_via_omniauth and make sure that it actually can save records to the database.

### CODE REVIEW

**Comment by anokhikastia** [comment]
Looks good to me. It passes the Cucumber test that we wrote. However, we still need to check whether it works locally when we login with Github. That check requires an additional fix.

**Comment by mrinasugosh** [comment]
Looks good to me. Out of curiosity, is the default access-level student if none is specified?

**Comment by willsheng** [comment]
looks good to me as well

**Comment by Laralinmcc** [comment]
Looks good!

**Comment by juwon-k** [comment]
Is there no PTID for this one?

**Comment by shteveno** [comment]
@juwon-k The PTID is on the cucumber tests but I will add it in the pull request description

**Pull request merged**
