### PR TITLE
Code refactor Problem_Minor.js

### PR DESCRIPTION
**Pull request by Laralinmcc**
#PTID: #152910521
Abstracted duplicate javascript code and segmented functions.

### CODE REVIEW

**Comment by juwon-k** [comment]
Is the commented legacy code unnecessary?

**Comment by mrinasugosh** [comment]
Looks good! Let's merge once the travis passes :)

**Comment by Laralinmcc** [comment]
Yes looked into it seemed like it was just left for no reason...

**Comment by juwon-k** [comment]
alright then lets ship

**Pull request merged**
