### PR TITLE
Update Clips Source to use Ajax for source copy

### PR DESCRIPTION
**Pull request by Laralinmcc**
PTID: #152774422
This commit contains the changes that allows for the source code that is copied to a users key board to obtained from an AJAX call rather than embedded in the view. This optimizes the rendering of the problems page as a text area with the source code does not need to be initially rendered.

### CODE REVIEW

**Comment by willsheng** [comment]
looks good

**Comment by mrinasugosh** [comment]
This doesn't include the PTID?

**Comment by shteveno** [comment]
@mrina24 Do we only have to include the PTID in the cucumber tests? If anything it would be good to add the PTID in a comment just to be safe.

**Comment by mrinasugosh** [comment]
@shteveno I believe we include PTID in cucumber tests and our Pull Request Description

**Comment by willsheng** [comment]
added PTID

**Comment by shteveno** [comment]
Everything looks good now, ship it!

**Comment by anokhikastia** [comment]
Looks good!

**Comment by willsheng** [comment]
looks great now

**Comment by mrinasugosh** [comment]
Everything looks good now :)

**Pull request merged**
