### PR TITLE
Asynchronous File Upload Epic

### PR DESCRIPTION
**Pull request by mrinasugosh**
Features in this branch:
-PTID: #152624684 Making Uploading Questions Asynchronous
-PTID: #153042872 While uploading questions users see animation
-PTID: #152624754 Redirecting to Respective View after Uploading Questions
-PTID: #152624808 Detecting Identical Questions after Uploading Questions
-PTID: #151852219 Optimize the response time on problems/collections renders (part of our solution for this)
At the moment, users can upload questions but if they upload more than 25 questions at a time the HTTP request times out. Then they don't know if the questions were even uploaded since the site crashes. Instead, a background worker like delayed job, sidekiq, or resque offloads this task. Then a series of AJAX calls are made from the view to the controller checking to see if the job is done. Once the job is done, then the view redirects to another view based on the outcome of the job.

Testing:
In order to fully automate the testing for asynchronous upload, we needed a testing suite which would allow us to follow a redirect to a different URI following the completion of queued ajax requests. Despite many hours of research, this could not be implemented by Juwon and I within the scope of the project, so we marked the test cases (both cucumber and rspec) where this would need to be implemented as pending. Our feature is working on heroku and locally, but the mechanism for testing it needs to be implemented by future teams working on this project.

### CODE REVIEW

**Comment by juwon-k** [comment]
In the future, we could make the commit logs less repetitive and more informative (just a note). Everything else looks great! Good work partner :')

**Comment by willsheng** [comment]
looks good to me, good work

**Comment by shteveno** [comment]
Amazing work, all five user stories look good!

**Comment by anokhikastia** [comment]
Looks great. Go ahead and merge.

**Comment by Laralinmcc** [comment]
This looks really great! Juwon is right cleaner commit logs are better, but I know this took a long time. Good work.

**Pull request merged**
